### ISSUE TITLE
Have specific version for each programming language

### ISSUE THREAD

**Issue by AbrahamGreenman** [razroo/codemorph#5]
E.g. break off @codemorph/angular to its own version as well as @codemorph/react to its own version. 

This will allow code morphs to be specific to each version level. @codemorph/core will act independently and will instead be a utils library used by other codemorphs

**Comment by giteshsarvaiya** [comment]
Is is completed ?

**Comment by CharGrnmn** [comment]
This is not albeit we can create new methods for new versions, so yes and no. https://github.com/razroo/codemorph/issues/10 makes sense to work on first. i am going to assign this issue to you
