### ISSUE TITLE
Enable effects to work on web

### ISSUE THREAD

**Issue by AbrahamGreenman** [razroo/codemorph#6]
Per README

> (Due to the nature of how effects work i.e. the need to take the entire file system into account
effects currently only work on the OS level. There are efforts from our side to make effects 
work on web and we hope to that feature available sooner than later.)

**Comment by giteshsarvaiya** [comment]
Hey Charlie! 
Can you guide me where and how can I learn the specific way to do this task ?

**Comment by CharGrnmn** [comment]
This one is complete already I am marking as done

**Comment by CharGrnmn** [comment]
Closing as complete

**Comment by CharGrnmn** [comment]
@giteshsarvaiya drop your twitter or LinkedIn. If interested in contributing i will open more issues here 💯

**Comment by giteshsarvaiya** [comment]
Twitter- @SarvaiyaGitesh
